Update README
ray-di/Ray.Di pull request #253
Opened 2022-02-06 09:45 UTC by koriym

* PHP8.1のコードに対応
* 最初から見直してクリーンアップ

2022-02-07 14:48 UTC, NaokiTsuchiya requested changes

2022-02-07 14:48 UTC, NaokiTsuchiya commented on README.ja.md
> +### 束縛トリビュートの定義
```suggestion
### 束縛アトリビュートの定義
```

2022-02-07 14:48 UTC, NaokiTsuchiya commented on README.ja.md
> +カスタムの `Qualifier`属性を、どのメソッドでもデフォルトで依存性を注入するようにするには、次のようにしますが属性を追加するには、 `RayDi⇄InjectInterface` を実装する必要があります。
namespace？

```suggestion
カスタムの `Qualifier`属性を、どのメソッドでもデフォルトで依存性を注入するようにするには、次のようにしますが属性を追加するには、 `Ray\Di\Di\InjectInterface` を実装する必要があります。
```

2022-02-07 14:55 UTC, NaokiTsuchiya commented on README.ja.md
>  [Provider bindings](http://code.google.com/p/rayphp/wiki/ProviderBindings) はインターフェイスと実装クラスの**プロバイダー**を束縛します。
歴史を感じるURLですが、参照できないようです。

```suggestion
```

2022-02-07 14:57 UTC, NaokiTsuchiya commented on README.ja.md
> +モジュールを使って、リンクバインディング、インスタンスバインディング、プロバイダバインディング、コンストラクタバインディング、アンターゲットバインディングを作成します。
バインディング = 束縛 ですが、表記が混在しているので統一してもいいかなと思いました。

2022-02-07 15:39 UTC, koriym commented on README.ja.md
> +モジュールを使って、リンクバインディング、インスタンスバインディング、プロバイダバインディング、コンストラクタバインディング、アンターゲットバインディングを作成します。
束縛で統一しました。

2022-02-08 14:24 UTC, merged

2022-02-08 14:24 UTC, koriym commented
@NaokiTsuchiya Thanks for the review!