Inject Provider with Set attribute
ray-di/Ray.Di pull request #262
Opened 2022-03-01 14:52 UTC by koriym

closes #261

2022-03-01 16:12 UTC, NaokiTsuchiya approved these changes
`Set` 以外は既存の機能（モジュールとProvider）を利用して実現できているのがすごいです！

2022-03-01 16:15 UTC, koriym commented
動的ファクトリー生成のインジェクトがたったこれだけで書けるのかという

2022-03-02 00:47 UTC, koriym commented on src/di/Injector.php
> +        $module->install(new InjectingProviderModule());
これだけ！

2022-03-02 01:06 UTC, NaokiTsuchiya requested changes

2022-03-02 01:06 UTC, NaokiTsuchiya commented on tests/di/Fake/FakeSet.php
> +
```suggestion
```

2022-03-02 04:55 UTC, NaokiTsuchiya approved these changes

2022-03-02 05:39 UTC, NaokiTsuchiya approved these changes

2022-03-02 05:39 UTC, NaokiTsuchiya approved these changes

2022-03-02 05:42 UTC, NaokiTsuchiya approved these changes

2022-03-02 05:46 UTC, NaokiTsuchiya approved these changes

2022-03-02 05:47 UTC, NaokiTsuchiya approved these changes

2022-03-02 05:54 UTC, merged